### PR TITLE
Add support for Laravel 8

### PR DESCRIPTION
**Pull request by MimisK13**
Add support for Laravel 8

### CODE REVIEW

**Comment by Daniyal-Javani** [comment]
Hi @mohamednagy 

Do you have any plan to merge the PR?

**Comment by chaseconey** [comment]
@mohamednagy any word on this?

**Comment by nagi1** [comment]
Hey, I love the thought and work you putted into this. But I feel it's a shame that it not supporting of Laravel  8.
There's a PR to add this. If you could please merge it.

BTW I'm totally welling to maintain this repo if you don't have enough free time :)

**Comment by mohamednagy** [comment]
@nagi1 Hey Ahmed, thanks for offering support here, unfortunately i don't have time atm to maintain the package, i really appreciate that, i added you as a maintainer.

**Comment by nagi1** [comment]
Thank you, for your valuable contribution. it now supports Laravel 8, please use 2.0

**Pull request closed without merging**
